---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: l5
  labels:
    app: postgres
data:
  POSTGRES_DB: testdatabase
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpassword
  PGDATA: /var/lib/postgresql/data/pgdata

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redmine-config
  namespace: l5
  labels:
    app: postgres
data:
  REDMINE_DB_POSTGRES: database
  REDMINE_DB_USERNAME: testuser
  REDMINE_DB_PASSWORD: testpassword
  REDMINE_DB_DATABASE: testdatabase
  REDMINE_SECRET_KEY_BASE: supersecretkey

...
