---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
  namespace: l5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - image: redmine:4.1.1
        name: redmine
        ports:
        - containerPort: 3000
        env:
        - name: REDMINE_DB_POSTGRES
          valueFrom:
            configMapKeyRef:
              name: redmine-config
              key:  REDMINE_DB_POSTGRES

        - name: REDMINE_DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: redmine-config
              key:  REDMINE_DB_USERNAME

        - name: REDMINE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key:  POSTGRES_PASSWORD

        - name: REDMINE_DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: redmine-config
              key:  REDMINE_DB_DATABASE

        - name: REDMINE_SECRET_KEY_BASE
          valueFrom:
            configMapKeyRef:
              name: secrets
              key: REDMINE_SECRET_KEY_BASE
        volumeMounts:
        - name: postgres-pvc
          mountPath: /var/lib/postgresql/data/
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: postgres-pvc
        persistentVolumeClaim:
          claimName: postgres-pvc

...