---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: l5
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
# если бы был https
#  tls:
#    - hosts:
#        - mysite.com
#      secretName: staging-iam-tls
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redmine
            port:
              number: 3000