---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: l4
  labels:
    app: postgres
data:
  POSTGRES_DB: testdatabase
  POSTGRES_USER: testuser
  PGDATA: /var/lib/postgresql/data/pgdata

...